managersystem/clients/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('budget/', views.budget, name='budget'),
]

managersystem/dashboard/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('notifications/', views.notifications, name='notifications'),
]

managersystem/managersystem/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.apps import apps

dashboard_name = apps.get_app_config('dashboard').verbose_name
stock_name = apps.get_app_config('stock').verbose_name
cashflow_name = apps.get_app_config('cashflow').verbose_name
clients_name = apps.get_app_config('clients').verbose_name
tickets_name = apps.get_app_config('tickets').verbose_name

urlpatterns = [
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/login'}, name='logout'),
    path('dashboard/', include(('dashboard.urls', dashboard_name), namespace='dashboard')),
    path('stock/', include(('stock.urls', stock_name), namespace='stock')),
    path('cashflow/', include(('cashflow.urls', cashflow_name), namespace='cashflow')),
    path('clients/', include(('clients.urls', clients_name), namespace='clients')),
    path('tickets/', include(('tickets.urls', tickets_name), namespace='tickets')),
    path('admin/', admin.site.urls),
]

managersystem/stock/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

managersystem/tickets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('newticket/', views.edit_ticket, name='edit_ticket'),
    path('newticket/saveticket/', views.save_ticket, name='save_ticket'),
    path('editticket/<int:ticket_id>/saveticket/', views.save_ticket,
        name='save_ticket'),
    path('editticket/<int:ticket_id>/', views.edit_ticket, name='edit_ticket'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('ticket/<int:ticket_id>/ticketajax/', views.ticket_ajax,
        name='ticket_ajax'),
    path('ticket/<int:ticket_id>/savecomment/', views.save_comment,
        name='save_comment'),
    path('ticket/<int:ticket_id>/deletecomment/', views.delete_comment,
        name='delete_comment'),
]

managersystem/core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

"""
    Contact Table: Abstract class representing personal info about an User or a
    Client.
"""
class Contact(models.Model):
    street = models.CharField(max_length=100, default="Rua .")
    neighbourhood = models.CharField(max_length=100, default="Calafate")
    number = models.IntegerField(default="80")
    postal_number = models.CharField(max_length=9, default="303000")
    phone = models.CharField(max_length=10, default="9999999")
    alt_phone = models.CharField(max_length=10, default="99999999")

    class Meta:
        abstract = True

"""
    User Table: Saves data about users who can perform actions on the manager
    system. There are three types of user: Admin, Manager and Common.
"""
class User(AbstractUser, Contact):
    add_date = models.DateTimeField('date added', auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        permissions = (
                ('ad', 'admin'),
                ('ma', 'manager'),
                ('co', 'common'),
        )

    def __str__(self):
        return self.get_username()

"""
    Stock Product Table: Registers data about the products physically available
    at the companie.
"""
class StockProduct(models.Model):
    name = models.CharField(max_length=50)
    quantitie = models.DecimalField(max_digits=10, decimal_places=2)

"""
    Activity Table: Base table which registers actions of creating new
    registers performed by any user.
"""
class Activity(models.Model):
    add_date = models.DateTimeField('date added', auto_now_add=True)
    added_by = models.ForeignKey(User, on_delete=models.PROTECT)

"""
    Client Table: Keeps data about a single client of the companhie which is
    registered as an action performed by an user.
"""
class Client(Activity, Contact):
    name = models.CharField(max_length=100)
    companie = models.CharField(max_length=200)
    email = models.CharField(max_length=100)

    def __str__(self):
        return self.name

"""
    Ticket Table: Registers a task assigned to an User. Registering it is
    modeled as an action performed by an User.
"""
class Ticket(Activity):
    title = models.CharField(max_length=200)
    description = models.TextField()
    deadline = models.DateField('date added', auto_now_add=False)
    done = models.BooleanField(default=False)
    closed = models.BooleanField(default=False)
    notified = models.BooleanField(default=False)
    doing = models.BooleanField(default=False)
    assignee = models.ForeignKey(User, on_delete=models.PROTECT)
    related_client = models.ForeignKey(Client, null=True, blank=True, on_delete=models.PROTECT)

    @property
    def get_cname(self):
        cname = "Ticket"
        return cname

    def __str__(self):
        return self.title

"""
    Comment Table: An abstract class for generic comments.
"""
class Comment(Activity):
    text = models.TextField()
    deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True

"""
    Ticket Comment Table: Concrete class for ticket's comments.
"""
class TicketComment(Comment):
    related_ticket = models.ForeignKey(Ticket, on_delete=models.PROTECT)

    def __str__(self):
        return self.text

"""
    Request Table: Registers a generical request from a client. It can be a Budget
    Request or an Order Request.
"""
class Request(Ticket):
    BUDGET = 'BG'
    ORDER = 'OD'
    REQ_TYPE = (
            (BUDGET, 'Pedido de orçamento'),
            (ORDER, 'Pedido de entrega'),
    )
    req_type = models.CharField(max_length=2, choices=REQ_TYPE, default=BUDGET)

    @property
    def get_cname(self):
        cname = "Requisição"
        return cname

    def __str__(self):
        return self.title

"""
    Cash Flow Table: Keeps data about an income or an expense. Registering is
    an action performed by an user.
"""
class CashFlow(Activity):
    INCOME = "IN"
    EXPENSE = "EX"
    FLOW = (
            (INCOME, 'Entrada de dinheiro'),
            (EXPENSE, 'Gasto de dinheiro'),
    )
    flow = models.CharField(max_length=2, choices=FLOW, default=INCOME)
    value = models.DecimalField(max_digits=8, decimal_places=2)
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

"""
    Budget Table: Registers a budget required by a client. Registering it is
    modeled as an action performed by an user. A Request can contain one or more
    Budgets.
"""
class Budget(Activity):
    PAGSEGURO = 'PS'
    TRANSACTION = 'TS'
    CASH = 'CS'
    PAY_OPT = (
            (PAGSEGURO, 'PAGSEGURO'),
            (TRANSACTION, 'Transferencia'),
            (CASH, 'Dinheiro'),
    )
    pay_opt = models.CharField(max_length=2, choices=PAY_OPT, default=PAGSEGURO)
    value = models.DecimalField(max_digits=8, decimal_places=2)
    req_days = models.IntegerField()
    req = models.ForeignKey(Request, on_delete=models.PROTECT)

"""
    Item Table: An Item is a component of the product required by the client,
    which is included on a budget. A Budget can contain 1 or more items.
"""
class Item(models.Model):
    item_name = models.CharField(max_length=30)
    quantitie = models.IntegerField()
    unit_value = models.DecimalField(max_digits=6, decimal_places=2)
    value = models.DecimalField(max_digits=6, decimal_places=2)
    budget = models.ForeignKey(Budget, on_delete=models.DO_NOTHING)

"""
    Order Table: Registers an Order required by a client. It is related to one
    budget and a Request can contain one or more Orders. An Order is registered
    as an action performed by an user.
"""
class Order(Activity):
    order_budget = models.OneToOneField(Budget, on_delete=models.PROTECT)
    final_value = models.DecimalField(max_digits=8, decimal_places=2)
    paid = models.BooleanField(default=False)
    canceled = models.BooleanField(default=False)
    order_requested_by = models.ForeignKey(Request, on_delete=models.PROTECT)

"""
    Expenditure Table: Registers a product Expenditure of a single product. It
    is registered as an action performed by an user.
"""
class Expenditure(Activity):
    product = models.OneToOneField(StockProduct, on_delete=models.PROTECT)
    quantitie = models.DecimalField(max_digits=8, decimal_places=2)

"""
    Log Table: Registers all actions related to alter the content of any
    action's registers performed by any user.
"""
class Log(models.Model):
    modified_at = models.DateTimeField('date modified', auto_now_add=True)
    modified_by = models.ForeignKey(User, on_delete=models.PROTECT)

    """
        Polimorphism to a class derivated from Activity
    """
    activity = models.ForeignKey(
            Activity,
            on_delete=models.PROTECT,
            related_name="%(app_label)s_%(class)s_updated_by",
    )

    def __str__(self):
        return "Edited by " + str(self.modified_by) + " at " + \
                str(self.modified_at.strftime('%d/%m/%y, %H:%M'))

managersystem/core/forms.py
from django import forms

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        widgets = {
                'password': forms.PasswordInput(),
        }

managersystem/core/views.py
from django.shortcuts import render

# Create your views here.

managersystem/core/templates/base.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
	<meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="{% static "img/apple-icon.png" %}">
	<link rel="icon" type="image/png" sizes="96x96" href="{% static "img/favicon.png" %}">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Craftec</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href={%static "css/bootstrap.min.css" %} rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static "css/animate.min.css" %}" rel="stylesheet"/>

    <!--  Paper Dashboard core CSS    -->
    <link href={%static "css/paper-dashboard.css" %} rel="stylesheet"/>

    <link href="{% static "css/demo.css" %}" rel="stylesheet" />
    <link rel="stylesheet"
        href="http://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    {% block static_head %}
    {% endblock %}

    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static "css/themify-icons.css" %}" rel="stylesheet">

</head>
<body>

    {% block modals %}
    {% endblock %}

    <div class="wrapper">
        <div class="sidebar" data-background-color="black" data-active-color="danger">
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="{% url "dashboard:index" %}" class="simple-text">
                        <img src="{% static "img/logo_craftec.png" %}" alt="Craftec"
                        height="35">
                    </a>
                </div>

                <ul class="nav">
                    {% if dashboard_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "dashboard:index" %}">
                            <i class="ti-panel"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    {% if clients_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "clients:index" %}">
                            <i class="ti-user"></i>
                            <p>Atendimento</p>
                        </a>
                    </li>
                    {% if tickets_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "tickets:index" %}">
                            <i class="ti-view-list-alt"></i>
                            <p>Tickets</p>
                        </a>
                    </li>
                    {% if budget_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "clients:budget" %}">
                            <i class="ti-receipt"></i>
                            <p>Orçamentos</p>
                        </a>
                    </li>
                    {% if cashflow_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "cashflow:index" %}">
                            <i class="ti-wallet"></i>
                            <p>Controle de Caixa</p>
                        </a>
                    </li>
                    {% if stock_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "stock:index" %}">
                            <i class="ti-map"></i>
                            <p>Controle de estoque</p>
                        </a>
                    </li>
                    {% if notifications_page %}
                        <li class="active">
                    {% else %}
                        <li>
                    {% endif %}
                        <a href="{% url "dashboard:notifications" %}">
                            <i class="ti-bell"></i>
                            <p>Notificações</p>
                        </a>
                    </li>
            </ul>
        </div>
    </div>
    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    {% block brand %}
                    {% endblock %}
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url "tickets:edit_ticket" %}">
                                <i class="ti-notepad"></i>
                                <p>Novo Ticket</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">{{ notify_count }}</p>
                                    <p>Notificações</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                  {% for notify in notifications %}
                                      <li><a href="#">
                                              {% if notify.request %}
                                                  Nova {{ notify.request.get_cname }}:
                                              {% else %}
                                                  Novo {{ notify.get_cname }}:
                                              {% endif %}
                                              {{ notify }}
                                      </a></li>
                                  {% endfor %}
                              </ul>
                        </li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-settings"></i>
                                <p>{{ user }}</p>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                              <li><a href="#">Editar info</a></li>
                              <li><a href="/logout">Logout</a></li>
                            </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock %}
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                        <li>
                            <a href="{% url "dashboard:index" %}">
                                Dashboard
                            </a>
                        </li>
                        <li>
                            <a href="http://craftec3d.com.br">
                               Craftec
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy; <script>document.write(new
                        Date().getFullYear())</script>, developed by <a
                    href="https://github.com/madc0ww">Adriano 'madc0ww' Mourão</a>
                </div>
            </div>
         </footer>
    </div>
</body>

<!--   Core JS Files   -->
<script src="{% static "js/jquery-3.3.1.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/jquery-ui.min.js" %}" type="text/javascript"></script>
<script src="{% static "js/bootstrap.min.js" %}" type="text/javascript"></script>

<!--  Checkbox, Radio & Switch Plugins -->
<script src="{% static "js/bootstrap-checkbox-radio.js" %}"></script>

<!--  Charts Plugin -->
<script src="{% static "js/chartist.min.js" %}"></script>

<!--  Notifications Plugin    -->
<script src={%static "js/bootstrap-notify.js" %}></script>

<!-- Paper Dashboard Core javascript and methods -->
<script src="{% static "js/paper-dashboard.js" %}"></script>
<script src="{% static "js/demo.js" %}"></script>

{% block scripts %}
{% endblock %}

</html>