managersystem/managersystem/urls.py
from django.urls import include, path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.apps import apps

dashboard_name = apps.get_app_config('dashboard').verbose_name
stock_name = apps.get_app_config('stock').verbose_name
cashflow_name = apps.get_app_config('cashflow').verbose_name
clients_name = apps.get_app_config('clients').verbose_name
tickets_name = apps.get_app_config('tickets').verbose_name

urlpatterns = [
    path('login/', auth_views.login, name='login'),
    path('logout/', auth_views.logout, {'next_page': '/login'}, name='logout'),
    path('dashboard/', include(('dashboard.urls', dashboard_name), namespace='dashboard')),
    path('stock/', include(('stock.urls', stock_name), namespace='stock')),
    path('cashflow/', include(('cashflow.urls', cashflow_name), namespace='cashflow')),
    path('clients/', include(('clients.urls', clients_name), namespace='clients')),
    path('tickets/', include(('tickets.urls', tickets_name), namespace='tickets')),
    path('admin/', admin.site.urls),
]

managersystem/stock/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

managersystem/tickets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('newticket/', views.edit_ticket, name='edit_ticket'),
    path('newticket/saveticket/', views.save_ticket, name='save_ticket'),
    path('editticket/<int:ticket_id>/saveticket/', views.save_ticket,
        name='save_ticket'),
    path('editticket/<int:ticket_id>/', views.edit_ticket, name='edit_ticket'),
    path('ticket/<int:ticket_id>/', views.ticket, name='ticket'),
    path('ticket/<int:ticket_id>/ticketajax/', views.ticket_ajax,
        name='ticket_ajax'),
    path('ticket/<int:ticket_id>/savecomment/', views.save_comment,
        name='save_comment'),
    path('ticket/<int:ticket_id>/deletecomment/', views.delete_comment,
        name='delete_comment'),
]

managersystem/tickets/models.py
from django.db import models

# Create your models here.

managersystem/tickets/forms.py
from django import forms
from core.models import Ticket, User, Client

class TicketForm(forms.Form):
    title = forms.CharField(
            label='Título',
            max_length=200,
            widget=forms.TextInput(attrs={
                'class': 'form-control border-input',
            }),
    )
    deadline = forms.DateField(
            label='Deadline',
            widget=forms.DateInput(attrs={
                'id': 'datepicker',
                'class': 'form-control border-input',
            }),
    )
    assignee = forms.ModelChoiceField(
            label='Responsável',
            queryset=User.objects.all(),
            empty_label='Selecione o responsável pela tarefa',
            widget=forms.Select(attrs={
                'class': 'form-control border-input',
            }),
    )
    related_client = forms.ModelChoiceField(
            label = 'Cliente',
            queryset=Client.objects.all(),
            empty_label='Selecione o cliente (opcional)',
            required=False,
            widget=forms.Select(attrs={
                'class': 'form-control border-input',
            }),
    )
    description = forms.CharField(
            label='Descrição',
            widget=forms.Textarea(attrs={
                'class': 'form-control border-input',
            }),
    )

    class Meta:
        model = Ticket

class TicketCommentForm(forms.Form):
    text = forms.CharField(
            label='Comentário',
            widget=forms.Textarea(attrs={
                'class': 'form-control border-input',
            }),
    )

    class Meta:
        model = Ticket

managersystem/tickets/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.template import loader
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, get_list_or_404
from core.view_utils import session_context
from core.models import Ticket, User, Client, Request, Log, TicketComment
from django.forms import formset_factory
from .forms import TicketForm, TicketCommentForm
import datetime

@login_required
def index(request):
    template = loader.get_template('tickets/index.html')

    not_tickets = Request.objects.filter(done=False)
    open_tickets = Ticket.objects.filter(
            assignee=request.user,
            doing=False,
            done=False,
            closed=False,
    ).exclude(id__in=not_tickets)
    doing_tickets = Ticket.objects.filter(
            assignee=request.user,
            doing=True,
            done=False,
            closed=False,
    ).exclude(id__in=not_tickets)

    context = session_context(request)

    context['open_tickets'] = open_tickets
    context['doing_tickets'] = doing_tickets
    context['tickets_page'] = True

    return HttpResponse(template.render(context, request))

@login_required
def edit_ticket(request, ticket_id=0):
    template = loader.get_template('tickets/newticket.html')

    context = session_context(request)
    is_new_ticket = True

    if ticket_id != 0:
        is_new_ticket = False
        ticket = get_object_or_404(Ticket, pk=ticket_id)
        initial = {
                'title': ticket.title,
                'assignee': ticket.assignee.pk,
                'deadline': ticket.deadline,
                'description': ticket.description,
        }
        context['form'] = TicketForm(initial=initial)
        context['ticket_name'] = 'T' + str(ticket.pk)
    else:
        context['form'] = TicketForm

    context['tickets_page'] = True
    context['is_new_ticket'] = is_new_ticket

    return HttpResponse(template.render(context, request))

@login_required
def save_ticket(request, ticket_id=0):
    if request.method == 'POST':
        user = get_object_or_404(User, username=request.user)

        form_assignee = get_object_or_404(
                User,
                pk=request.POST.get('assignee'),
        )

        if request.POST.get('related_client'):
            form_related_client = Client.objects.get(
                    pk=request.POST.get('related_client'),
            )
        else:
            form_related = None

        form_description = request.POST.get('description')
        form_title = request.POST.get('title')

        if ticket_id != 0:
            form_deadline = request.POST.get('deadline')

            ticket = Ticket.objects.get(pk=ticket_id)
            ticket.assignee = form_assignee
            ticket.related_client = form_related
            ticket.deadline = form_deadline
            ticket.description = form_description
            ticket.title = form_title

            """
                Log the ticket edition
            """
            edition_log = Log(
                    modified_by=user,
                    activity=ticket,
            )
            edition_log.save()

        elif not Ticket.objects.filter(title=request.POST.get('title')):
            form_deadline = datetime.datetime.strptime(
                    request.POST.get('deadline'),
                    "%m/%d/%Y",
                    ).strftime("%Y-%m-%d")

            ticket = Ticket(
                    description=form_description,
                    title=form_title,
                    deadline=form_deadline,
                    done=False,
                    notified=False,
                    assignee=form_assignee,
                    related_client=form_related,
                    added_by=user,
            )
        ticket.save()
        return HttpResponseRedirect('/tickets/ticket/' + str(ticket.pk) + '/')
    return HttpResponseRedirect('tickets/edit_ticket/' + str(ticket_id) + '/')

@login_required
def save_comment(request, ticket_id):
    if request.method == 'POST':
        commentor = get_object_or_404(User, username=request.user)
        ticket = get_object_or_404(Ticket, pk=ticket_id)
        form_text = request.POST.get('text')

        comment = TicketComment(
                added_by=commentor,
                text=form_text,
                related_ticket=ticket,
        )
        comment.save()

    return HttpResponseRedirect('/tickets/ticket/' + str(ticket_id) + '/')


@login_required
def ticket(request, ticket_id):
    template = loader.get_template('tickets/ticket.html')

    ticket = get_object_or_404(Ticket, pk=ticket_id)
    comments = TicketComment.objects.filter(
            related_ticket_id=ticket_id,
            deleted=False,
    )

    if not ticket.notified:
        ticket.notified = True
        ticket.save()

    context = session_context(request)
    context['ticket'] = ticket
    context['tickets_page'] = True
    context['form'] = TicketCommentForm

    if comments.count() > 0:
        context['comments'] = comments

    try:
        log = Log.objects.filter(activity=ticket).latest('modified_at')
        context['log'] = log
    except:
        pass

    return HttpResponse(template.render(context, request))

@login_required
def ticket_ajax(request, ticket_id):
    ticket = Ticket.objects.get(
            pk=ticket_id,
    )

    data = {}
    action = request.GET.get('action', None)

    if action == 'change_done':
        ticket.done = not ticket.done
        ticket.save()

        element = '#trUndo'
        if ticket.done:
            element = '#trDone'
    elif action == 'change_closed':
        ticket.closed = not ticket.closed
        ticket.save()

        element = '#trClosed'
        if ticket.closed:
            element = '#trOpen'
    elif action == 'change_doing':
        ticket.doing = not ticket.doing
        ticket.save()

        element = '#trDoing'
        if ticket.doing:
            element = '#trBacklog'

    if action == 'change_done' or \
            action == 'change_closed' or \
            action == 'change_doing':
        data['status_changed'] = True
        data['element'] = element

        """
            Log the ticket edition
        """
        edition_log = Log(
                modified_by=request.user,
                activity=ticket,
        )
        edition_log.save()

        data['log'] = edition_log.__str__()


    return JsonResponse(data)

def delete_comment(request, ticket_id):
    data = {}
    if request.method == 'POST':
        comment_id = request.POST.get('comm_pk', None)

        ticket = Ticket.objects.filter(pk=ticket_id)
        comment = TicketComment.objects.get(
                pk=int(comment_id),
        )

        owner = User.objects.get(pk=comment.added_by.pk)

        if request.user == owner:
            comment.deleted = True
            comment.save()

        data['deleted'] = comment.deleted

    return JsonResponse(data)

managersystem/tickets/templates/tickets/index.html
{% extends 'base.html' %}
{% load static %}

{% block brand %}
<a class="navbar-brand" href="{% url "tickets:index" %}">Tickets</a>
{% endblock %}

{% block content %}
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Em andamento</h4>
                                <p class="category"><a href="#">Procurar Ticket</a></p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover">
                                    <thead>
                                        <th>ID</th>
                                    	<th>Título</th>
                                    	<th>Cliente</th>
                                    	<th>Deadline</th>
                                    	<th>Responsável</th>
                                    </thead>
                                    <tbody>
                                        {% for ticket in doing_tickets %}
                                            <tr>
                                                <td class="text-warning">
                                                    <a href="{% url "tickets:ticket" ticket.pk%}"
                                                        class="text-warning">
                                                        T{{ ticket.pk }}
                                                    </a>
                                                </td>
                                                <td class="text-warning">
                                                    <a href="{% url "tickets:ticket" ticket.pk%}"
                                                        class="text-warning">
                                                        {{ ticket.title }}
                                                    </a>
                                                </td>
                                                <td class="text-warning">{{ ticket.client }}</td>
                                                <td class="text-warning">{{ ticket.deadline }}</td>
                                                <td class="text-warning">{{ ticket.assignee }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Backlog</h4>
                                <p class="category"><a href="#">Procurar Ticket</a></p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover">
                                    <thead>
                                        <th>ID</th>
                                    	<th>Título</th>
                                    	<th>Cliente</th>
                                    	<th>Deadline</th>
                                    	<th>Responsável</th>
                                    </thead>
                                    <tbody>
                                        {% for ticket in open_tickets %}
                                            <tr>
                                                <td class="text-success">
                                                    <a href="{% url "tickets:ticket" ticket.pk%}"
                                                        class="text-success">
                                                        T{{ ticket.pk }}
                                                    </a>
                                                </td>
                                                <td class="text-success">
                                                    <a href="{% url "tickets:ticket" ticket.pk%}"
                                                        class="text-success">
                                                        {{ ticket.title }}
                                                    </a>
                                                </td>
                                                <td class="text-success">{{ ticket.client }}</td>
                                                <td class="text-success">{{ ticket.deadline }}</td>
                                                <td class="text-success">{{ ticket.assignee }}</td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
{% endblock %}

managersystem/tickets/templates/tickets/ticket.html
{% extends 'base.html' %}
{% load static %}
{% load markdown_deux_tags %}

{% block brand %}
<a class="navbar-brand" href="{% url "tickets:index" %}">Tickets</a>
{% endblock %}

{% block modals %}
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close"
                        data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Adicionar Comentário</h4>
                </div>
                <div class="modal-body">
                    <form action="savecomment/" method="post">
                        {% csrf_token %}
                        {{ form.text }}
                        * Utilize markdown para editar seu texto
                        <br/>
                        <br/>
                        <div class="text-center">
                            <button type="submit" class="btn btn-info
                                btn-fill btn-wd" value="Submit" >
                                    Enviar Comentário
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="content">
                            <div class="container-fluid">
                                <div class="row">
                                    <div class="col-md-10">
                                        <h3 class=title><span class="text-info">
                                            T{{ ticket.pk }} - {{ ticket.title }}
                                        </span>
                                        </h3>
                                        <p class="category">
                                            {% if ticket.closed%}
                                                <a  href="#"
                                                    id="trClosed"
                                                    class="text-danger"
                                                    >
                                                    Fechado
                                                </a>
                                            {% else %}
                                                <a  href="#"
                                                    id="trOpen"
                                                    class="text-success"
                                                    >
                                                    Aberto
                                                </a>
                                            {% endif %}
                                         - Criado por {{ ticket.added_by }} em {{ ticket.add_date }}</p>
                                    </div>
                                    <div class="col-md-2">
                                        <div class="text-right">
                                            <a  href=
                                            "{% url "tickets:edit_ticket" ticket.pk %}"
                                                id="trEdit"
                                                >
                                                Editar ticket
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <br/>
                                <br/>
                                <br/>
                                <div class="row">
                                    <div class="col-md-3">
                                        <div class="typo-line">
                                            <h5><span class="category">
                                                    <span
                                                        class="text-info">Responsável</span>
                                                </span>
                                                {{ticket.assignee}}
                                            </h5>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="typo-line">
                                            <h5><span class="category">
                                                    <span
                                                        class="text-info">Deadline</span>
                                                </span>
                                                {{ticket.deadline}}
                                            </h5>
                                        </div>
                                    </div>
                                    <div class="col-md-3">
                                        <div class="typo-line">
                                            <h5><span class="category">
                                                    <span
                                                        class="text-info">Estado</span>
                                                </span>
                                                {% if ticket.doing %}
                                                    <a href="#"
                                                        id="trDoing"
                                                        class="text-warning">
                                                        Em andamento
                                                    </a>
                                                {% else %}
                                                    <a href="#"
                                                        id="trBacklog"
                                                        class="text-success">
                                                        Backlog
                                                    </a>
                                                {% endif %}
                                            </h5>
                                        </div>
                                        <div class="col-md-3">
                                        {% if ticket.client %}
                                            <div class="typo-line">
                                                <h5><span class="category">
                                                        <span class="text-info">Cliente</span>
                                                    </span>
                                                    {{ticket.client}}
                                                </h5>
                                            </div>
                                        {% endif %}
                                    </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="typo-line">
                                            <h5><span class="category">
                                                    <span class="text-info">Descrição</span>
                                                </span>
                                                {{ ticket.description|markdown }}
                                            </h5>
                                        </div>
                                    </div>
                                </div>
                                <br/>
                                <br/>
                                <br/>
                                <div class="row">
                                    <div class="col-md-10", id="ticketLog">
                                        {% if log %}
                                            <p>{{ log }}</p>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-2">
                                        <div class="text-right">
                                            {% if ticket.done %}
                                                <a href="#"
                                                    id="trUndo"
                                                    class="text-success">
                                                    Tarefa Feita
                                                </a>
                                            {% else %}
                                                <a  href="#"
                                                    id="trDone"
                                                    >
                                                    Marcar como feito
                                                </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                                <br/>
                                <br/>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% if comments %}
                {% for comm in comments %}
                    <div class="row" id="comm-{{ comm.pk }}">
                        <div class="col-md-2">
                        </div>
                        <div class="col-md-8">
                            <div class="card">
                                <div class="content">
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col-md-10">
                                            </div>
                                            {% if user == comm.added_by %}
                                                <div class="col-md-2">
                                                    <button type="button"
                                                        id="close-{{ comm.pk }}"
                                                        class="close">&times;</button>
                                                </div>
                                            {% endif %}
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="typo-line">
                                                    <h5><span class="category">
                                                        <span class="text-info">
                                                            {{ comm.added_by }}
                                                        </span>
                                                    </span></h5>
                                                    {{ comm.text|markdown }}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12 text-right
                                                text-info">
                                                {{ comm.add_date }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-2">
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            <div class="text-center">
                <button type="button" class="btn btn-info btn-fill btn-wd"
                                      data-toggle="modal"
                                      data-target="#myModal">
                    Adicionar Comentário
                </button>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "js/responsive.js" %}"></script>
    <script>
        $(document).on('click', "[id^=tr]", function() {
            elem = $(this).attr("id");
            changeTicketStatus(
                '#'+elem,
                changeActions[elem].action,
                "{% url "tickets:ticket_ajax" ticket.pk %}",
                {{ ticket.pk }},
                changeActions[elem].newelem
            );
        });

        $("[id^=close-]").on('click', function() {
            elem = $(this).attr("id");
            removeComment(
                elem,
                "{% url "tickets:delete_comment" ticket.pk %}"
            );
        });
    </script>
{% endblock %}